Improve blockchain basics
vechain/vechain-docs pull request #61
Opened 2024-07-12 10:40 UTC by fabiorigam

2024-07-12 18:12 UTC, victhorbi requested changes
Great work!

2024-07-12 18:12 UTC, victhorbi commented on blockchain-basics/README.md
> +Welcome to the frontier of digital innovation. This concise guide illuminates the transformative world of blockchain technology, a cornerstone of the emerging Web3 era. We'll journey through the core
```suggestion
Blockchain is an immense subject, depending on the level of detail, explaining could require from few seconds up to months. 
With a short introduction, we would like to scratch the surface of the transformative world of blockchain technology and mention why we speak of Web3. 
Even if groundbreaking applications are a reality, and distributed ledger system are reshaping our digital landscape, we want to enroll you to become a pioneer of what still remains uncovered, hoping that you will choose VeChain as your home.
```

2024-07-15 08:57 UTC, nwbrettski approved these changes
LGTM. I like the decentralized orchestra explanation, hadn't come across that one before.

2024-07-15 09:11 UTC, victhorbi approved these changes

2024-07-15 09:16 UTC, merged