update dapp-kit docs
vechain/vechain-docs pull request #82
Opened 2024-10-29 09:31 UTC by davidecarpini

2024-10-29 10:01 UTC, victhorbi requested changes

2024-10-29 10:01 UTC, victhorbi commented on developer-resources/sdks-and-providers/dapp-kit/dapp-kit-1/vanilla/usage.md
> +* `accountDomain` - the  account vechain domain if present
```suggestion
* `accountDomain` - the .vet domain account (VeChain domains) if present
```

2024-10-29 14:09 UTC, davidecarpini commented on developer-resources/sdks-and-providers/dapp-kit/dapp-kit-1/core/usage.md
> +  //OPTIONAL: you can choose witch wallet to be allowed between 'wallet-connect', 'veworld', 'sync2' or 'sync'. default: all
thanks

2024-10-29 14:15 UTC, davidecarpini commented on developer-resources/sdks-and-providers/dapp-kit/dapp-kit-1/core/usage.md
> +* `accountDomain` - the  account vechain domain if present
thanks

2024-10-29 14:15 UTC, davidecarpini commented on developer-resources/sdks-and-providers/dapp-kit/dapp-kit-1/react/usage.md
> +            // OPTIONAL: certificate to be signed during the login, otherwise a standard one will be used
thanks

2024-10-29 14:16 UTC, davidecarpini commented on developer-resources/sdks-and-providers/dapp-kit/dapp-kit-1/react/usage.md
> +    // The account vechain domain if present
thanks

2024-10-29 14:16 UTC, davidecarpini commented on developer-resources/sdks-and-providers/dapp-kit/dapp-kit-1/react/usage.md
> +This hook can fetch a vechain domain from an address and an address from a vechian domain.
thanks

2024-10-29 14:16 UTC, davidecarpini commented on developer-resources/sdks-and-providers/dapp-kit/dapp-kit-1/vanilla/usage.md
> +    // OPTIONAL: certificate to be signed during the login, otherwise a standard one will be used
thanks

2024-10-29 14:17 UTC, davidecarpini commented on developer-resources/sdks-and-providers/dapp-kit/dapp-kit-1/vanilla/usage.md
> +    //OPTIONAL: you can choose witch wallet to be allowed between 'wallet-connect', 'veworld', 'sync2' or 'sync'. default: all
thanks

2024-10-29 14:17 UTC, davidecarpini commented on developer-resources/sdks-and-providers/dapp-kit/dapp-kit-1/vanilla/usage.md
> +* `accountDomain` - the  account vechain domain if present
thanks

2024-10-30 11:12 UTC, victhorbi approved these changes

2024-10-30 14:08 UTC, merged

2025-01-03 16:53 UTC, victhorbi reviewed
LGTM