Improve account abstraction docs
vechain/vechain-docs pull request #87
Opened 2024-12-23 17:51 UTC by fabiorigam

2025-01-03 18:23 UTC, victhorbi requested changes

2025-01-03 18:23 UTC, victhorbi commented on core-concepts/account-abstraction/account-factory-contract.md
> +Each Account Factory contract is independently deployed and configured, tailored to the specific requirements of the associated Account contract. Smart contract wallet providers may implement distinc
```suggestion
Each Account Factory contract is independently deployed. Each smart contract wallet provider may create their own Account Factory tailored to their specific requirements. The Smart Account contract that gets deployed may also be different.
```

2025-01-03 18:23 UTC, victhorbi commented on core-concepts/account-abstraction/useroperation.md
> +A UserOperation is the key data structure of account abstraction. It represents a new type of transaction that is generated by the user, processed by the EntryPoint contract and verified by the Accou
Are you totally sure? 
I would say that it's verified by the bundler, while the actual transaction is verified and processed by the entry point contract.

2025-01-03 18:23 UTC, victhorbi commented on core-concepts/account-abstraction/bundler.md
> +A Bundler plays a crucial role in the account abstraction ecosystem by continuously monitoring a public mempool for UserOperations created by user. Its primary responsibility is to collect these User
It's correct, I'm reformulating the first part to avoid people thinking that the mempool is creted by the user.
```suggestion
A Bundler plays a crucial role in the account abstraction architecture. Its primary responsibility is to collect these UserOperations from a public mempool, bundle them together, and pass them to the EntryPoint contract for execution.
```

2025-01-03 18:23 UTC, victhorbi commented on core-concepts/account-abstraction/bundler.md
> +The `EntryPoint contract` serves as a "global trusted singleton," meaning it is a single, universally trusted smart contract within the blockchain ecosystem. This contract handles incoming transactio
```suggestion
The `EntryPoint contract` serves as a "global trusted singleton," meaning it is a single, universally trusted smart contract within the blockchain ecosystem.  In reality it's not like that, in a public blockchain anyone can create and promote its EP, do your own research and trust the EP you can find on trusted websites only.
This contract handles incoming transactions, validates them, and manages the execution of UserOperations. The Bundler acts as the intermediary between users and the EntryPoint contract, ensuring UserOperations are properly packaged and processed.
```

2025-01-07 08:21 UTC, fabiorigam commented on core-concepts/account-abstraction/useroperation.md
> +A UserOperation is the key data structure of account abstraction. It represents a new type of transaction that is generated by the user, processed by the EntryPoint contract and verified by the Accou
You're right: [52bda61](https://github.com/vechain/vechain-docs/pull/87/commits/52bda619225c8dcbe30a32c9e51883ab1e2f737e) just fixed it

2025-03-19 13:20 UTC, victhorbi approved these changes
LGTM

2025-03-19 13:21 UTC, merged